### ISSUE TITLE
ModuleNotFoundError: No module named 'Engine.th_utils.io'

### ISSUE THREAD

**Issue by CHMimilanlan** [TaoHuUMD/StructLDM#6]
After running `bash scripts/renderpeople.sh 0`
Errors occurred with following traceback output:

Traceback (most recent call last):
  File "/data/xch/Avatar/3D/StructLDM/generation.py", line 19, in <module>
    opt = ProjectOptions().parse_()
  File "/data/xch/Avatar/3D/StructLDM/struct_decoder/options/test_option.py", line 13, in parse_
    opt = self.parse()
  File "/data/xch/Avatar/3D/StructLDM/struct_decoder/options/options.py", line 480, in parse
    self.merge_cfg(self.opt)
  File "/data/xch/Avatar/3D/StructLDM/struct_decoder/options/options.py", line 449, in merge_cfg
    from Engine.th_utils.io.prints import printd
ModuleNotFoundError: No module named 'Engine.th_utils.io'

It seams that there is no module named io under Directory "Engine.th_utils", I have carefully checked all files, but didn't find files or directory named "io", and also didn't find functions named "printd". 

Is there a file missing mistake? I will be grateful for your timely response!

**Comment by TaoHuUMD** [comment]
fixed.

**Comment by CHMimilanlan** [comment]
thanks!
