### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/asset/uv_sampler/smpl_fbx_template.obj'

### ISSUE THREAD

**Issue by CHMimilanlan** [TaoHuUMD/StructLDM#7]
Error occurred after running command `bash scripts/renderpeople.sh 0`
I didn't find file "smpl_fbx_template.obj" under 'assert' directory which you provided on OneDrive. 

 test   [0]
CustomDatasetDataLoader
load dataset  renderpeople
('create test dataset',)
dataset [renderpeople] was created
test_results_renderpeople test_results_renderpeople
StructLDM.struct_decoder.models.model_eva_autodecoder_GAN
Traceback (most recent call last):
  File "/data/xch/Avatar/3D/StructLDM/generation.py", line 58, in <module>
    model = create_model(opt).cuda()
  File "/data/xch/Avatar/3D/StructLDM/struct_decoder/models/create_model.py", line 14, in create_model
    model.initialize(opt)
  File "/data/xch/Avatar/3D/StructLDM/../StructLDM/struct_decoder/models/model_eva_autodecoder_GAN.py", line 61, in initialize
    self.render_posmap = Index_UV_Generator(self.uv_reso, self.uv_reso, uv_type=self.opt.df.uv_type, data_dir= os.path.join(self.opt.data_dir, "asset/uv_sampler"))
  File "/data/xch/Avatar/3D/StructLDM/Engine/th_utils/animation/uv_generator.py", line 74, in __init__
    verts_uvs, faces_uvs = self.get_faces_uvs(os.path.join(self.data_dir, self.obj_file))
  File "/data/xch/Avatar/3D/StructLDM/Engine/th_utils/animation/uv_generator.py", line 97, in get_faces_uvs
    verts, faces, aux = load_obj(obj_path)        
  File "/data/xch/tools/anaconda/envs/chm/lib/python3.10/site-packages/pytorch3d/io/obj_io.py", line 223, in load_obj
    with _open_file(f, path_manager, "r") as f:
  File "/data/xch/tools/anaconda/envs/chm/lib/python3.10/site-packages/pytorch3d/io/utils.py", line 26, in _open_file
    f = path_manager.open(f, mode)
  File "/data/xch/tools/anaconda/envs/chm/lib/python3.10/site-packages/iopath/common/file_io.py", line 1062, in open
    bret = handler._open(path, mode, buffering=buffering, **kwargs)  # type: ignore
  File "/data/xch/tools/anaconda/envs/chm/lib/python3.10/site-packages/iopath/common/file_io.py", line 645, in _open
    return open(  # type: ignore
FileNotFoundError: [Errno 2] No such file or directory: 'data/asset/uv_sampler/smpl_fbx_template.obj'

could you please provide this file? I will be grateful for your timely response!

**Comment by TaoHuUMD** [comment]
You can download these files from [data/asset](https://1drv.ms/f/c/cd958c29ffd57ddb/EhBoSdYizdVPkjyy85LDkM8BQzbRM1BFIlkrxtwwbH1_hA?e=LvZmCU)

**Comment by CHMimilanlan** [comment]
thanks!
